### ISSUE TITLE
iCabMobile support

### ISSUE THREAD

**Issue by tristan-k** [LorenzoPane/browserdefault#12]
Using the bundle id ```de.icab.iCabMobile``` in the custom browser section doesnt work properly. Links will get opened with a ```http://(null)``` in front of it.

**Comment by LorenzoPane** [comment]
I don’t own this app, so I can’t test it.  Have you tried putting `x-icabmobile://x-callback-url/open?url*=` in for `URL Scheme`?

**Comment by tristan-k** [comment]
I tried bur it stil the same behaviour.

**Comment by LorenzoPane** [comment]
Sorry, but I'm not sure what to do.  I don't own this app, so I can't test it.

**Comment by tristan-k** [comment]
Anything else I can provide?

**Comment by LorenzoPane** [comment]
If you would like to send me your discord, I might be able to work with you on this later today or tomorrow.

**Comment by LorenzoPane** [comment]
I'm closing this as I haven't heard from you in over a week.  Get back in touch if you would like to work with me on this.

**Comment by m-hume** [comment]
Using the URL scheme
x-icabmobile://x-callback-url/open?url=
Worked for me (no bundle I'd needed)
Nice one. x

**Comment by LorenzoPane** [comment]
Resolved in 061c0cf
