### ISSUE TITLE
Links opening wrong from apps (specifically AirMail)

### ISSUE THREAD

**Issue by mogui666** [LorenzoPane/browserdefault#15]
![30DCEF73-CC63-4FDD-A0CB-71B2CB59B5EA](https://user-images.githubusercontent.com/25361391/58356166-eeaee680-7eb9-11e9-99ad-3214f7cdae09.png)

as you can see it adds a “http//“ before the link

**Comment by LorenzoPane** [comment]
What browser is it opening in?

**Comment by mogui666** [comment]
Chrome

**Comment by LorenzoPane** [comment]
Thanks.  I'm having trouble recreating this because I do not own this app, and it is paid.  Have you noticed this problem when opening links from any other apps?

**Comment by mogui666** [comment]
yeah it also does the same thing opening from notes app

**Comment by LorenzoPane** [comment]
I'm not able to recreate this.  Are you on version 1.9.0?

**Comment by mogui666** [comment]
yep i’m on the latest version. No matter what link i open, from any app, it’ll open the link wrong like that. Here’s an example of a wrong link https://https//github.com/LorenzoPane/browserdefault

**Comment by mogui666** [comment]
and also, it only started happening after 1.9.0 update.

**Comment by LorenzoPane** [comment]
I'm looking into this, but I'm having trouble recreating it on my device.  I need to leave shortly, but I'll take a further look once I find the time.  Until then, you can downgrade to whatever version worked best for you in the [/StableBuilds](https://github.com/LorenzoPane/browserdefault/tree/master/StableBuilds) directory.

**Comment by lighbothe** [comment]
> Thanks. I'm having trouble recreating this because I do not own this app, and it is paid. Have you noticed this problem when opening links from any other apps?

Chrome is paid? What? It is fully free

**Comment by LorenzoPane** [comment]
> > Thanks. I'm having trouble recreating this because I do not own this app, and it is paid. Have you noticed this problem when opening links from any other apps?
> 
> Chrome is paid? What? It is fully free

AirMail is paid.  He later clarified that this was occurring when opening links from other apps as well.

**Comment by LorenzoPane** [comment]
Wow.  Turns our the reason I couldn't recreate it was because I pushed the wrong deb :/.  Silly me.  LMK if it is fixed [here](https://github.com/LorenzoPane/browserdefault/blob/master/StableBuilds/com.lpane.browserdefault_1.9.0_iphoneos-arm.deb)

**Comment by mogui666** [comment]
it’s fixed now :) Thank you! love this tweak.
