### ISSUE TITLE
'Open In' option from third party apps doesn't open proper url

### ISSUE THREAD

**Issue by LorenzoPane** [LorenzoPane/browserdefault#2]
From u/peiartila on reddit:

>I discovered a bug.
When I am using a third-party app that detects that I have a third-party browser installed and gives me the option of opening content in that third-party browser (when that browser is configured as the default browser), the URL passed on to the browser is blank.
For example, I have Firefox installed and configured as the default browser. If I use a third-party app like Smart News, it detects that Firefox is installed and gives me the option to open articles in Firefox.
When I choose Firefox, the URL is blank. When I choose Safari, the URL loads properly in Firefox.
Currently using version 1.6.0-1+debug.
Thanks

**Comment by Huyaos** [comment]
-
