### ISSUE TITLE
I couldn't find url format in UCbroswer

### ISSUE THREAD

**Issue by Skilling-Kiss** [LorenzoPane/browserdefault#23]
com.ucweb.iphone.lowversion
but url is useless,plz tell me！ths!

**Comment by LorenzoPane** [comment]
URL schemes are created and maintained by the developer of the app, not me.  Some do not support them and some are poorly documented.  Do some searching around the internet to try to find one that works with this app.  While you're searching, take a  look at some documented security risks with UC Browser and determine whether it is something you want to be using in the first place..

**Comment by Skilling-Kiss** [comment]
yeah,I've find it, ucbrowser:// .
Ths for replay!
