### ISSUE TITLE
Links sent to Firefox ignore everything after “&”

### ISSUE THREAD

**Issue by rcnino** [LorenzoPane/browserdefault#25]
This is most noticeable in Mail where marketing email links are tracked. 

For example: [https://allbirds.us12.list-manage.com/track/click?u=b15f1d2ea8a562ce4325b69bd&id=58668639e3&e=5ff52ff273](https://allbirds.us12.list-manage.com/track/click?u=b15f1d2ea8a562ce4325b69bd&id=58668639e3&e=5ff52ff273) gets sent to Firefox as [https://allbirds.us12.list-manage.com/track/click?u=b15f1d2ea8a562ce4325b69bd](https://allbirds.us12.list-manage.com/track/click?u=b15f1d2ea8a562ce4325b69bd) and fails to load the page.

**Comment by LorenzoPane** [comment]
I'll take a look when I get home.  It sounds like I should've enabled percent escape encoding for firefox.  Try a custom config with:
Bundle ID: `org.mozilla.ios.Firefox`
URL Scheme: `firefox://open-url?url=https://`
Percent Escapes: `On`

TBH BrowserDefault is a mess. I originally hacked it together for one person. I never expected it to have thousands of users.  Folks kept asking for shit, so I would just write some garbage code and increment the version by .1 (yuck). I'm likely going to rewrite it sometime soon.

**Comment by rcnino** [comment]
That works! Thanks for the suggestion. I tried to do this using info from [Firefox for iOS](https://github.com/mozilla-mobile/firefox-ios-open-in-client) but left off "https://".

It might not be perfect but it gets the job done, and it's the only working browser changer on 12.4. Regardless of what you think of the code, implementing a mechanism to add any browser is smart and solved my issue without a version update. Keep it up!
