### ISSUE TITLE
A12x support

### ISSUE THREAD

**Issue by Flynnsworth** [LorenzoPane/browserdefault#26]
Is this planned?

**Comment by LorenzoPane** [comment]
This should already be supported as of ae05798ea64ed9b45f440448694e135fb3c6b284.  Are you having any problems?

**Comment by Flynnsworth** [comment]
After installation it does not show in settings

**Comment by LorenzoPane** [comment]
Are you installing from packix?

**Comment by Flynnsworth** [comment]
Yes. From packix via Cydia

**Comment by LorenzoPane** [comment]
Version 1.9.7?

**Comment by Flynnsworth** [comment]
Yes

**Comment by LorenzoPane** [comment]
Very strange... Are other tweaks' preferences working okay?  I assume Preference Loader and Rocket Bootstrap are both installed and up to date?

**Comment by Flynnsworth** [comment]
Watusi needs Preference Loader to run and that’s working fine. RocketBootstrap 1.0.6 is installed but says iOS12 not supported yet. Maybe that’s the issue.

**Comment by LorenzoPane** [comment]
I do not have access to an a12 device to test with, but I know of multiple a12 users who aren't having problems.  I don't know the details, but you may need to download cephei, and/or ensure that RocketBootstrap and PreferenceLoader are both installed and up to date from http://rpetri.ch/repo.  Afaik, 1.07~b5 of the latter from his repo *is* supported on 12.

**Comment by Flynnsworth** [comment]
A newer beta of PreferenceLoader was required from rpetri.

It is now working. Cheers

**Comment by LorenzoPane** [comment]
Great!
