### ISSUE TITLE
Opens weird tab on screenshot

### ISSUE THREAD

**Issue by OmgImAlexis** [LorenzoPane/browserdefault#27]
When screenshotting in chrome with chrome set as the default I’m thrown to this page.

![65E6AA9A-79D6-4A9D-AD2C-789AE5B9CEB5](https://user-images.githubusercontent.com/6525926/71047825-00751580-218d-11ea-9773-78ddb619c130.png)

**Comment by LorenzoPane** [comment]
I may take a look at this when I have some time.  I haven't been actively developing this project in some time and I plan on working on a more stable, extensible, and powerful sequel once I find some free time.

**Comment by nathancahill** [comment]
I'm getting lots of escaping issues recently. Especially query parameters, often the first query parameter is included, and the rest are dropped.

**Comment by LorenzoPane** [comment]
Sorry, I haven't found time to look at this yet. What iOS version are you on?

**Comment by LorenzoPane** [comment]
Also, could you send me a few links that produce reproducible improper results?

**Comment by nathancahill** [comment]
Sure. iOS 13.

Here's a link: http://httpbin.org/anything?first=1&second=2

**Comment by LorenzoPane** [comment]
Thanks. I'll take a look sometime soon. I'm assuming that with the large SpringBoard changes in iOS 13, they changed launching applications via the home screen to use `FBSystemServiceOpenApplicationRequest` which they didn't do in iOS 12. I currently don't have an iOS 13 device to test on, but updating has been on my todo list. My only worry is backwards compatibility since many people are staying on 12 until there is a semi-untether, and a few devices are EOL on 12.

**Comment by nathancahill** [comment]
It actually looks like entering the Firefox details as a custom browser and choosing Use Percent Escapes solves my issue. Launching Safari is a different one, I can open a second issue.

**Comment by LorenzoPane** [comment]
Sounds good.

**Comment by LorenzoPane** [comment]
@OmgImAlexis Are you on iOS 13 as well? I'm unable to reproduce this on iOS 12.

**Comment by OmgImAlexis** [comment]
Yes, I don't currently have a jailbroken device as I upgraded to a iPhone 11 but when I was on `13.1.*` and `13.2.*` I had the same issue on both my iPhone 7 and iPhone 7+.

**Comment by LorenzoPane** [comment]
Thanks. It looks like `FBSystemServiceOpenApplicationRequest` is used much more liberally in iOS 13.
