### ISSUE TITLE
Preference Bundle Issue for A12 devices

### ISSUE THREAD

**Issue by SimonAlparaz** [LorenzoPane/browserdefault#3]
On an iPhone XS 12.1.2. The deb installs fine through Sileo but gives the infamous "Preference Bundle Issue" when going into the settings.

I assume it just needs to be updated for A12. Thanks!
![IMG_5949](https://user-images.githubusercontent.com/7918492/57057466-c2f36480-6c5d-11e9-809d-81e78bdf180d.PNG)

**Comment by LorenzoPane** [comment]
Sorry I'm getting to this late.  My understanding is that preference bundles need to be fixed on the user's device.  See [https://www.reddit.com/r/jailbreak/comments/bj3tyj/update_all_of_my_maintained_tweaks_were_updated/](https://www.reddit.com/r/jailbreak/comments/bj3tyj/update_all_of_my_maintained_tweaks_were_updated/).

**Comment by SimonAlparaz** [comment]
My apologies, I should have specified that I've done those steps and I do have preferences working with other tweaks.

I could be misunderstanding what I've read (as I'm not a tweak dev) but I believe the tweaks also need to be recompiled with arm64e added in the Makefile?

**Comment by LorenzoPane** [comment]
Are you using version [1.8.0](https://github.com/LorenzoPane/browserdefault/blob/master/StableBuilds/com.lpane.browserdefault_1.8.0-1%2Bdebug_iphoneos-arm.deb)?  It is recompiled with arm64e support.

**Comment by SimonAlparaz** [comment]
Yes, Sileo shows the package version as "1.8.0-1+debug". I have also reinstalled the tweak, rebooted, rejailbroke, reinstalled RocketBootstrap + PreferenceLoader, and ran iCleaner for good measure. Still get the same error try and get into the settings page.

Have others reported this issue? It could very well end up being something on my end, but ~20 other tweaks' preferences are working for me right now. (Thanks for the work, by the way! I don't want to come off as complaining, haha.)

**Comment by LorenzoPane** [comment]
Testing is difficult since I’m not on a12, so the 1.8.0 build is actually untested on a12, despite it boasting support :p.  It is likely a problem on my end.  Nobody else has reported this, but I don’t have very many users :p.  Someone forked my repo to add support a couple days ago, so I’ll take a look at what they did once I get home.

**Comment by LorenzoPane** [comment]
Sorry about the wait; I've been terribly busy.  Should be fixed in eda34c1.

**Comment by SimonAlparaz** [comment]
No problem! Awesome, it's working perfectly on my device now. :D
Thanks a bunch, appreciate the work!
