### ISSUE TITLE
Opera touch doesn’t load pages

### ISSUE THREAD

**Issue by Wayner84** [LorenzoPane/browserdefault#32]
I’ve got an issue where when I click a link it will open opera and the link looks correct but it says it can’t load the webpage. When I look at the url it is full of numbers and percents, any idea what’s going on?

**Comment by LorenzoPane** [comment]
Looks like Opera changed how they handle URL Schemes. To fix, use the `Custom` option with:
BundleID = `com.opera.OperaTouch`
URL Scheme = `touch-https://`
Percent Escapes = `off`
As a note. I am not officially supporting iOS 13 yet so functionality may be sporadic.

**Comment by Wayner84** [comment]
Thank you very much! Solved the issue
