### ISSUE TITLE
Aloha And Alook

### ISSUE THREAD

**Issue by saeidselfjoor** [LorenzoPane/browserdefault#5]
hi I use bundle id and browserdefult just open alook browser not the link please add alook and aloha as defult they both great and many people using them thank you

**Comment by LorenzoPane** [comment]
Please read the Readme.md before posting an issue.  The tweak is working as intended.  To add support for aloha enter `alohabrowser://open?link=` for the `URL Scheme` section in the preference bundle.  I don't own Alook, so I can't test it, but try entering `Alook://` for `URL Scheme`.  If I find the time, I'll add presets.
