### ISSUE TITLE
Yandex

### ISSUE THREAD

**Issue by 1vsALL** [LorenzoPane/browserdefault#6]
Please Yandex Browser

**Comment by LorenzoPane** [comment]
You can enable Yandex by doing the following:
- Go into the preferences
- Under `Default Browser` select `Custom (specify options below)`
- Under `Bundle ID` type `ru.yandex.mobile.search`
- Under `URL Scheme (if applicable)` type `yandexbrowser-open-url://`
- Enable `Use Percent Escapes`
