### ISSUE TITLE
Handoff browser link

### ISSUE THREAD

**Issue by jefro108** [LorenzoPane/browserdefault#7]
Is it possible for this to work with the Handoff browser link? - it still opens in Safari, even though the browser being used on my Mac is Chrome!

**Comment by LorenzoPane** [comment]
I've been fairly busy lately, so I can't make any promises, but I'll take a look once I find the time.

**Comment by jefro108** [comment]
Thanks 😊

**Comment by GsIgUi** [comment]
I have this problem too

**Comment by LorenzoPane** [comment]
This seems to be working now
